var consts = {
    STARS_SPEED: 6000,
    MOVEMENT_SPEED: 5,
    SHOT_SIZE: 10,
    SHOTS_COUNT: 3,
    SHIP_WIDTH: 30,
    SHIP_HEIGHT: 40,
    METEOR_WIDTH: 60,
    METEOR_HEIGHT: 60,
    METEORS_COUNT: 8,
    GAME_WIDTH: 313,
    GAME_HEIGHT: 500,
    COLLISION_PIXELS: 6,
    GAME_SPEED: 30
};
